Return-Path: <info-3PEuUv0fcce@h2opoint.com>
Received: from KKD0717VHU (203.146.109.71) by vpn-control-198.fainttank.com id h46i7e1tovsf for <info-3PEuUv0@chiefsubpoena.com>; Tue, 23 Sep 2014 01:08:40 -0700 (envelope-from <info-3PEuUv0fcce@h2opoint.com>)
Message-ID: <3871352590.6858225522.55547881.0.8A7F9833.1002@chiefsubpoena.com>
Date: Tue, 23 Sep 2014 15:07:04 +0700
From: Elena <info-3PEuUv0fcce@h2opoint.com>
To: info-3PEuUv0@chiefsubpoena.com
Subject: I am very bored, let's talk?
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary="----=_Part_58009229_5866543140.2319625052453"
List-Unsubscribe: http://mail.h2opoint.com/do?p=un&m=d0dd763c29ebf6edef4d3a3b310441b57f49e26426a19b5afe1da377d9e7e0eff0

------=_Part_58009229_5866543140.2319625052453
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

Hello! I am very bored, let's talk? My name is Elena, I'm 23 years old, I'mfrom Ukraine, looking for young man

I'm online now http://datingtothow.ru/?profile=964E83B02FE96A03248B8CB07F388&from=info-3PEuUv0


------=_Part_58009229_5866543140.2319625052453
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" =
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns=3D"http://www.w3.org/1999/xhtml">

<head>
<meta content=3D"en-us" http-equiv=3D"Content-Language" />
<meta content=3D"text/html; charset=3Dutf-8" http-equiv=3D"Content-Type" =
/>
<title>Private Chat</title>
</head>

<body>

<p>Hello! I am very bored, let's talk? My name is Elena, I'm 23 years =
old, I'm
from Ukraine, looking for young man</p>
<p><a =
href=3D"http://datingtothow.ru/?profile=3D964E83B02FE96A03248B8CB07F388&f=
rom=3Dinfo-3PEuUv0">I'm online now</a></p>

</body>

</html>


------=_Part_58009229_5866543140.2319625052453--