                                                                                                                                                                                                                                                               
Delivered-To: nick@mediauniversal.com
Received: by 10.25.146.21 with SMTP id u21csp464184lfd;
        Tue, 23 Sep 2014 13:04:44 -0700 (PDT)
X-Received: by 10.70.128.1 with SMTP id nk1mr2554568pdb.97.1411502683491;
        Tue, 23 Sep 2014 13:04:43 -0700 (PDT)
Return-Path: <service@theclub.trunkclub.com>
Received: from omp.theclub.trunkclub.com (omp.theclub.trunkclub.com. [199.7.206.167])
        by mx.google.com with ESMTP id r4si11360426pds.150.2014.09.23.13.04.42
        for <nick@mediauniversal.com>;
        Tue, 23 Sep 2014 13:04:43 -0700 (PDT)
Received-SPF: pass (google.com: domain of service@theclub.trunkclub.com designates 199.7.206.167 as permitted sender) client-ip=199.7.206.167;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of service@theclub.trunkclub.com designates 199.7.206.167 as permitted sender) smtp.mail=service@theclub.trunkclub.com;
       dkim=pass header.i=@theclub.trunkclub.com;
       dmarc=pass (p=NONE dis=NONE) header.from=theclub.trunkclub.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=trunkclub; d=theclub.trunkclub.com;
 h=MIME-Version:Content-Type:Date:To:From:Reply-To:Subject:List-Unsubscribe:Message-ID; i=service@theclub.trunkclub.com;
 bh=E2/LXvlROZ4OCqj7FM6XUqw4QJk=;
 b=lTH4gpGBI4Nlu31Nlv/YTMJrYL0gfDMd06t3cHXOUw67ysdVR4iA8Cx57tnJ0mQBwpOPiZA6wwOJ
   pkSIOqLezQV5WzUr35XbTFdJxP7OBz8+N5WUoNgcEmdQ9c66zHI5mGBNDLzguljskr7S1W/8/Pp6
   nSHTaKKYZjkbGgPTGk4=
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=trunkclub; d=theclub.trunkclub.com;
 b=A1z8NiCuSW1g13cARiWQ0DlL9MOmtxmbtgK2LOwjjeXwWXOC/RSmUCedLgrx6w1Jf6LbqC3M342Y
   YnjlN6t/aTupojm5w+vZ3eP5dFPkBlYZIfNBevwUK3/jTlbx6r6VwtP5WG1jqFpdkbgKy+DnycKj
   U2T6FnPRQkXLfiRMbAc=;
Received: by omp.theclub.trunkclub.com id h4795m1607go for <nick@mediauniversal.com>; Tue, 23 Sep 2014 13:04:36 -0700 (envelope-from <service@theclub.trunkclub.com>)
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----msg_border_vJIfNhkUj6"
Date: Tue, 23 Sep 2014 13:04:36 -0700
To: nick@mediauniversal.com
From: "Mary Houlihan" <service@theclub.trunkclub.com>
Reply-To: "Mary Houlihan" <mary@trunkclub.com>
Subject: 5 Fall Favorites
List-Unsubscribe: <https://theclub.trunkclub.com/pub/optout/UnsubscribeOneStepConfirmAction?YES=true&_ri_=X0Gzc2X%3DWQpglLjHJlYQGu7vWlUueJ8ustHD064D0B2pva9Azdairedbw&_ei_=EolaGGF4SNMvxFF7KucKuWO1AprnsXfb8XO866Tv3U1ntIHCsC7xkr-TtqJeZS2FtK5pJlbB8_gGxBct6M>, <mailto:unsubscribe-WQpglLjHJlYQGu7vWlUueJ8ustHD064D0B2pva9Azdairedbw@imh.rsys5.com?subject=List-Unsubscribe>
X-sgxh1: gpJsxuLKpHmgpNLjkHtQJhu
X-rext: 4.interact5.EmBN4t3mLcCmkla9RAW9R7TiNHD6ZHpjLKIO
X-cid: trnkclb.100545
Message-ID: <0.0.5F.9DE.1CFD76999A5E456.0@omp.theclub.trunkclub.com>

This is a multi-part message in MIME format.

------msg_border_vJIfNhkUj6
Date: Tue, 23 Sep 2014 13:04:36 -0700
Content-Type: multipart/alternative; boundary="----alt_border_GdKj5BwvV4_1"



------alt_border_GdKj5BwvV4_1
Content-Type: text/plain;
  charset="ISO-8859-1"
Content-Transfer-Encoding: quoted-printable

Trunk Club=20

The Fall Transition, with Jason Smith=20

September 23, 2014=20

According to a classic holiday song=2E December is the most wonderful=20
time of the year=2E We respectfully disagree=2E=20

During the fall, the cooler weather allows for maximum wardrobe flexibility=
=2E Sweaters, coats, blazers, scarves - and=20
any combination thereof - all come into play=2E If you're Jason Smith, VP o=
f Merchandising at Trunk Club, the new season also means Pinot=20
Noir and plenty of firewood=2E As we head into the best time of the year fo=
r dressing, we asked Jason to share his favorites for fall, clothing-relate=
d and otherwise=2E You'll find his notes below=2E=20

I Want Fall Clothing=20


https://theclub=2Etrunkclub=2Ecom/pub/cc?_ri_=3DX0Gzc2X%3DWQpglLjHJlYQGu7vW=
lUueJ8ustHD064D0B2pva9AzdairedbwVXtpKX%3DTSTAY&_ei_=3DEv_YTMfnCoE7yY4W7cyz-=
g8PixxlDb9lOyeR0fKf7VWfUYcoICJhe9NaqQ362_KQhy0QtRmlkXiJm9OcRg=2EJg%3D%3D
=20

Jason Smith, VP of Merchandising=20

Statement Sweaters
Back in college, any time I knew I would be interacting with ladies, I wore=
 my Fair Isle shawl-collar sweater=2E=20
Because of its unique look, the sweater helped me stand out against the ste=
ady backdrop of Abercrombie that the other guys wore=2E Even if your colleg=
e days (much like mine) are now long gone, introducing a few strong sweater=
s into your rotation is a good move that can result in some well-deserved a=
ttention=2E=20

First Impressions
I'm especially proud of the variety of outerwear that our merchandising tea=
m has put together for fall=2E Sometimes guys overlook the importance of ou=
terwear and stick with their performance fleeces or ski parkas, but there i=
s always a better option=2E Your coat, jacket, or vest might be the last th=
ing you put on before you leave the house, but it's one of the first things=
 people notice=2E=20

Great Britain, Great Fabric
I have never been to Ireland or the Scottish Highlands, but that doesn't st=
op me from=20
dressing like I own country estates in both locations=2E The Brits=20
discovered that tweed and other sturdy fabrics stood up against cold=20
winds coming off the moors=2E Lucky for us, those same fabrics keep=20
Americans equally warm when temperatures drop on our side of the=20
Atlantic=2E=20

=22Football=22 and Neck Scarves
Scarves do a great job of balancing style and function=2E In addition to ke=
eping the chill off your neck, they add a sophisticated dimension to your o=
utfit=2E I prefer the slip knot because it's simple and practical=2E It's a=
lso the preferred knot of Europe's best-dressed soccer coaches, and it work=
s just as well for me while I watch Griffin, my two-year-old son, play in h=
is Lil' Kickers soccer league=2E=20

Everything Old Is New Again
For me, fall means nesting time=2E My family, the fireplace, and Pinot Noir=
 all factor into that=2E I also recently inherited my father's old vinyl=20
collection=2E Beyond listening to the same records that my father used to b=
last on weekend mornings (the man refused to let me sleep in), I've started=
 to build my own collection=2E =22Paul's Boutique=22 by the Beastie Boys an=
d =22Purple Rain=22 by Prince are my two favorite acquisitions so far=2E=20

I Want Fall Clothing=20


https://theclub=2Etrunkclub=2Ecom/pub/cc?_ri_=3DX0Gzc2X%3DWQpglLjHJlYQGu7vW=
lUueJ8ustHD064D0B2pva9AzdairedbwVXtpKX%3DTSTAY&_ei_=3DEv_YTMfnCoE7yY4W7cyz-=
g8PixxlDb9lOyeR0fKf7VWfUYcoICJhe9NaqQ362_KQhy0QtRmlkXiJm9OcRg=2EJg%3D%3D
=20

Reach Me Anytime=20
Mary Houlihan=20
mary=40trunkclub=2Ecom=20
214=2E306=2E4899

3010 N Henderson Ave=2E Dallas, TX


View in your web browser=20

https://theclub=2Etrunkclub=2Ecom/pub/sf/ResponseForm?_ri_=3DX0Gzc2X%3DWQpg=
lLjHJlYQGu7vWlUueJ8ustHD064D0B2pva9AzdairedbwVXMtX%3DWQpglLjHJlYQGmPtoFzbBq=
4eiI3JBc4oB5RzbJe71vt63uR284&_ei_=3DEv_YTMfnCoE7yY4W7cyz-g8PixxlDb9lOyeR0fK=
f7VWfUYcoICJhe9NaqQ362_KQhy0QtRmlkXiJm9OcRg
=20
=2E=20

Unsubscribe=20
https://theclub=2Etrunkclub=2Ecom/pub/optout?_ri_=3DX0Gzc2X%3DWQpglLjHJlYQG=
u7vWlUueJ8ustHD064D0B2pva9Azdairedbw&_ei_=3DEolaGGF4SNMvxFF7KucKuWO1AprnsXf=
b8XO866Tv3U1ntIHCsC7xkr-TtqJeZS2FtK5pJlbB8_gGxBct6M=20
from our newsletters=2E=20

Trunk Club=20
325 West Ohio Street=20
Chicago, IL 60654

------alt_border_GdKj5BwvV4_1
Content-Type: text/html;
  charset="ISO-8859-1"
Content-Transfer-Encoding: quoted-printable

<=21DOCTYPE html PUBLIC =22-//W3C//DTD HTML 4=2E01 Transitional//EN=22 =22h=
ttp://www=2Ew3=2Eorg/TR/html4/loose=2Edtd=22>
<html lang=3D=22en=22>
<head><META NAME=3D=22ROBOTS=22 CONTENT=3D=22NOINDEX, NOFOLLOW=22>
    <meta http-equiv=3D=22Content-Type=22 content=3D=22text/html; charset=
=3DUTF-8=22>
    <meta http-equiv=3D=22Cache-Control=22 content=3D=22no-cache; max-age=
=3D0=22>
    <meta name=3D=22viewport=22 content=3D=22initial-scale=3D1=2E0=22/>   <=
=21-- So that mobile webkit will display zoomed in -->
    <meta name=3D=22format-detection=22 content=3D=22telephone=3Dno;address=
=3Dno;email=3Dno=22>
  =09
  =09

      <title>Trunk Club</title>=20
<style type=3D=22text/css=22>
  /* Resets: see reset=2Ecss for details */
  =2EReadMsgBody =7B width: 100%; background-color: =23e6e6e6;=7D
  =2EExternalClass =7Bwidth: 100%; background-color: =23e6e6e6;=7D
  =2EExternalClass, =2EExternalClass p, =2EExternalClass span, =2EExternalCl=
ass font, =2EExternalClass td, =2EExternalClass div =7Bline-height:100%;=7D
  body =7B-webkit-text-size-adjust:none; -ms-text-size-adjust:none;=7D
  body =7Bmargin:0; padding:0;=7D
  table =7Bborder-spacing:0;=7D
  table td =7Bborder-collapse:collapse;=7D
  =2Eyshortcuts a =7Bborder-bottom: none =21important;=7D
  =2Epreheader =7B display:none =21important; visibility:hidden; opacity:0; =
color:transparent; height:0; width:0; =7D
  =2Ebodycopy=7Btext-align:center; font-size: 16px;font-family: Georgia, 'Ti=
mes New Roman', serif; line-height: 24px;=7D

  /* Make sure bg is still visible on mobile */
  =40media screen and (max-width: 600px) =7B
    table=5Bclass=3D=22container=22=5D =7B
      width: 95% =21important;
    =7D
  =7D

  /* Less padding on mobile */
  =40media screen and (max-width: 480px) =7B
    td=5Bclass=3D=22container-padding=22=5D =7B
      padding: 15px =21important;
    =7D
  =09
    td=5Bclass=3D=22copyblock=22=5D =7B
      padding: 10px =21important;
    =7D
  =09
    span=5Bclass=3D=22bodycopy=22=5D =7B
      font-size: 14px =21important;
      line-height: 20px =21important;

    =7D
  =09
    span=5Bclass=3D=22headline=22=5D =7B
      font-size: 20px =21important;
      line-height: 24px =21important;
    =7D
  =09
  =7D
=09
  /* unzoom view on Windows Phones */
  =40media (max-width: 400px) =7B
    =40-ms-viewport =7B
      width: 320px =21important;
    =7D
  =7D


  /* Class changes for mobile */
  =40media only screen and (max-width : 600px) =7B

    /* force container columns to (horizontal) blocks */
    td=5Bclass=3D=22force-col=22=5D =7B
      display: block;
      padding-right: 0 =21important;
      width: 100% =21important;
      height: auto =21important;
    =7D
=09
    table=5Bclass=3D=22col-2=22=5D =7B
      /* unset table align=3D=22left/right=22 */
      float: none =21important;
      width: 100% =21important;
      height: auto =21important;

    =7D

    /* resize images based on size */
    img=5Bclass=3D=22fluidimage=22=5D =7B=20
      height:auto =21important;=20
      width:100% =21important;
      max-width: 520px =21important;
    =7D
  =09
    /* resize images based on size */
    img=5Bclass=3D=22logo=22=5D =7B=20
      height:auto =21important;=20
      width:100% =21important;
      max-width: 140px =21important;
    =7D
  =09
    /* blocks that will be hidden on mobile */
    td=5Bclass=3D=22hidethis=22=5D =7B
      display: none =21important;
    =7D
  =09
  =7D
      </style>
</head>

<body=20
  style=3D=22background-color: =23f3f3f3; color: =23000000; font-family: Hel=
vetica, Arial, Sans-Serif; font-size:12px; margin: 0; padding: 0;=22=20
  text=3D=22=23000000=22 bgcolor=3D=22=23f3f3f3=22 leftmargin=3D=220=22 topm=
argin=3D=220=22 marginwidth=3D=220=22 marginheight=3D=220=22
>


<table border=3D=220=22 style=3D=22background-color: =23f3f3f3; width: 100%=
;=22 width=3D=22100%=22 border=3D=220=22 cellpadding=3D=220=22 cellspacing=
=3D=220=22 bgcolor=3D=22=23f3f3f3=22>
  <tr>
    <td align=3D=22center=22 class=3D=22container-padding=22 style=3D=22paddi=
ng: 30px;=22>
      <a href=3D=22https://theclub=2Etrunkclub=2Ecom/pub/cc?_ri_=3DX0Gzc2X%3DW=
QpglLjHJlYQGu7vWlUueJ8ustHD064D0B2pva9AzdairedbwVXtpKX%3DTRAAY&_ei_=3DEv_YT=
MfnCoE7yY4W7cyz-g8PixxlDb9lOyeR0fKf7VWfUYcoICJhe9NaqQ362_KQhy0QtRmlkXiJm9Oc=
Rg=2E=22 style=3D=22color: =23555555; font-size: 24px; font-weight: bold; t=
ext-decoration: none;=22>
        <span class=3D=22preheader=22 style=3D=22display: none =21important; vi=
sibility: hidden; opacity: 0; color: transparent; height: 0; width: 0;=22>T=
he Fall Transition with J=2E Smith </span>  =09
        <img class=3D=22logo=22 src=3D=22http://trunkclub-assets=2Es3=2Eamazona=
ws=2Ecom/emails/assets/logo=2Ejpg=22 border=3D=220=22 width=3D=22140=22 alt=
=3D=22Trunk Club=22 style=3D=22border: none;=22>
      </a>
    </td>
  </tr>
=09
  <tr>
      =09
    <td style=3D=22font-family:Arial,Helvetica,Sans-serif;background-color:=
=23f3f3f3;=22 align=3D=22center=22 valign=3D=22top=22 bgcolor=3D=22=23f3f3f=
3=22>
          =09
      <=21-- White background container -->
      <table width=3D=22600=22 class=3D=22container=22 style=3D=22background-c=
olor: =23ffffff; font-family: Georgia, 'Times New Roman', serif; color: =23=
000000;border: 1px solid =23dddddd;=22 border=3D=220=22 bgcolor=3D=22=23fff=
fff=22 cellpadding=3D=220=22 cellspacing=3D=220=22 border=3D=220=22>
        <tr>
        =09
          <td class=3D=22container-padding=22 bgcolor=3D=22=23ffffff=22 align=3D=
=22left=22 valign=3D=22top=22 style=3D=22padding: 40px;=22>
          =09
            <=21-- Main Email Body -->
            <table border=3D=220=22 class=3D=22columns-container=22 style=3D=22ba=
ckground-color: =23ffffff; =22 bgcolor=3D=22=23ffffff=22 border=3D=220=22 c=
ellpadding=3D=220=22 cellspacing=3D=220=22>
            =09
              <tr>
                <td class=3D=22force-col=22 valign=3D=22top=22>
            =09
                  <img class=3D=22fluidimage=22 width=3D=22520=22 src=3D=22https://s=
tatic=2Ecdn=2Eresponsys=2Enet/i5/responsysimages/trnkclb/contentlibrary/adh=
oc2014/2014-09/20140919_Fall/images/FallTransitionHero=2Ejpg=22 style=3D=22=
display:block; color: =23555555; font-size: 24px; font-weight: bold; text-d=
ecoration: none;=22 border=3D=220=22 alt=3D=225-Pocket Chinos=22 />
            =09
                </td>
              </tr>

              <tr>
                <td class=3D=22spacer25=22 height=3D=2225=22 align=3D=22center=22>
                </td>
              </tr>
            =09
              <tr>
                <td align=3D=22center=22 class=3D=22dateline=22 style=3D=22border-t=
op: 1px solid =23dddddd; border-bottom: 1px solid =23dddddd; text-align:cen=
ter; font-size: 9px;font-family: Verdana, Helvetica, Arial, sans-serif; tex=
t-transform: uppercase; font-weight: bold; color: =23999999; letter-spacing=
: 1px; padding: 10px 0 10px 0;=22>
                  September 23, 2014
                </td>
              </tr>
            =09
              <tr>
                <td align=3D=22center=22 class=3D=22copyblock=22 style=3D=22padding=
: 20px;=22>
                  <span class=3D=22bodycopy=22 style=3D=22text-align:center; font-si=
ze: 16px;font-family: Georgia, 'Times New Roman', serif; line-height: 24px;=
=22>
                    <i>According to a classic holiday song=2E December is the most wo=
nderful time of the year=2E We respectfully disagree=2E</i><br/>
                    <br/>
                    During the fall, the cooler weather allows for maximum wardrobe f=
lexibility=2E Sweaters, coats, blazers, scarves - and any combination there=
of - all come into play=2E<br/><br/>
                    If you're Jason Smith, VP of Merchandising at Trunk Club, the new=
 season also means Pinot Noir and plenty of firewood=2E As we head into the=
 best time of the year for dressing, we asked Jason to share his favorites =
for fall, clothing-related and otherwise=2E You'll find his notes below=2E
                  </span>
                </td>
              </tr>
            =09
              <tr>
                <td class=3D=22spacer20=22 height=3D=2220=22 align=3D=22center=22>
                </td>
              </tr>
            =09
              <tr>
                <td align=3D=22center=22 class=3D=22trunkbutton=22>
                  <table border=3D=220=22 cellpadding=3D=220=22 cellspacing=3D=220=
=22 height=3D=2231=22 style=3D=22height: 31px;margin: 0;padding: 0;=22>
                    <tr>
                      <td align=3D=22center=22 valign=3D=22middle=22 style=3D=22border=
: 2px solid =23000000; font-family: Verdana, Helvetica, Arial, sans-serif;f=
ont-weight: bold;font-size: 9px;text-transform: uppercase;padding: 10px 12p=
x;letter-spacing: 1px;text-align: center;=22>
                        <a href=3D=22https://theclub=2Etrunkclub=2Ecom/pub/cc?_ri_=3DX0=
Gzc2X%3DWQpglLjHJlYQGu7vWlUueJ8ustHD064D0B2pva9AzdairedbwVXtpKX%3DTSTAY&_ei=
_=3DEv_YTMfnCoE7yY4W7cyz-g8PixxlDb9lOyeR0fKf7VWfUYcoICJhe9NaqQ362_KQhy0QtRm=
lkXiJm9OcRg=2E=22 style=3D=22color: =23000000 =21important; text-decoration=
: none;=22>
                          I Want Fall Clothing
                        </a>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            =09
              <tr>
                <td class=3D=22spacer5=22 height=3D=225=22 align=3D=22center=22>
                </td>
              </tr>
          =09
            </table>
        =09
          </td>
        </tr>

      </table>
      <=21-- End White background Container-->
  =09
      <table>=20
        <tr>
          <td height=3D=2220=22 align=3D=22center=22>
          </td>
        </tr>
      </table>=09
    =09
      <=21-- White background container -->
      <table width=3D=22600=22 class=3D=22container=22 style=3D=22background-c=
olor: =23ffffff; font-family: Georgia, 'Times New Roman', serif; color: =23=
000000;border: 1px solid =23dddddd;=22 border=3D=220=22 bgcolor=3D=22=23fff=
fff=22 cellpadding=3D=220=22 cellspacing=3D=220=22 border=3D=220=22>
        <tr>
        =09
          <td class=3D=22container-padding=22 bgcolor=3D=22=23ffffff=22 align=3D=
=22left=22 valign=3D=22top=22 style=3D=22padding: 40px;=22>
          =09
            <=21-- Main Email Body -->
            <table border=3D=220=22 class=3D=22columns-container=22 style=3D=22ba=
ckground-color: =23ffffff; =22 bgcolor=3D=22=23ffffff=22 border=3D=220=22 c=
ellpadding=3D=220=22 cellspacing=3D=220=22>
            =09
      =09
            =09
              <tr>
                <td class=3D=22force-col=22 valign=3D=22top=22>
                  <img class=3D=22fluidimage=22 width=3D=22520=22 src=3D=22https://s=
tatic=2Ecdn=2Eresponsys=2Enet/i5/responsysimages/trnkclb/contentlibrary/adh=
oc2014/2014-09/20140919_Fall/images/DOJS_Sweaters_Email=2Ejpg=22 style=3D=
=22display:block; border: 0;=22 border=3D=220=22 alt=3D=22Frontier Pockets=
=22 />      =09
                </td>
              </tr>
            =09
              <tr>
                <td class=3D=22spacer10=22 height=3D=2210=22 align=3D=22center=22>
                </td>
              </tr>


=09
              <tr>
                <td class=3D=22imgcaption=22 align=3D=22left=22 style=3D=22font-siz=
e: 14px;font-family: Georgia, 'Times New Roman', serif; line-height: 24px;=
=22><span style=3D=22font-size: 13px; font-family: Verdana, Helvetica, Aria=
l, san-serif; line-height: 24px; text-transform:uppercase;font-weight:bold=
=22>statement sweaters</span><br/>
                  Back in college, any time I knew I would be interacting with ladie=
s, I wore my Fair Isle shawl-collar sweater=2E Because of its unique look, =
the sweater helped me stand out against the steady backdrop of Abercrombie =
that the other guys wore=2E Even if your college days (much like mine) are =
now long gone, introducing a few strong sweaters into your rotation is a go=
od move that can result in some well-deserved attention=2E
                </td>
              </tr>

              <tr>
                <td class=3D=22spacer40=22 height=3D=2240=22 align=3D=22center=22>
                </td>
              </tr>
            =09
            =09
            =09
            =09
              <tr>
                <td class=3D=22force-col=22 valign=3D=22top=22>
                  <img class=3D=22fluidimage=22 width=3D=22520=22 src=3D=22https://s=
tatic=2Ecdn=2Eresponsys=2Enet/i5/responsysimages/trnkclb/contentlibrary/adh=
oc2014/2014-09/20140919_Fall/images/DOJS_Outerwear_Email=2Ejpg=22 style=3D=
=22display:block; border:0;=22 border=3D=220=22 />      =09
                </td>
              </tr>
            =09
              <tr>
                <td class=3D=22spacer10=22 height=3D=2210=22 align=3D=22center=22>
                </td>
              </tr>

=09
              <tr>
                <td class=3D=22imgcaption=22 align=3D=22left=22 style=3D=22font-siz=
e: 14px;font-family: Georgia, 'Times New Roman', serif; line-height: 24px;=
=22><span style=3D=22font-size: 13px; font-family: Verdana, Helvetica, Aria=
l, san-serif; line-height: 24px; text-transform:uppercase;font-weight:bold=
=22>first impressions</span><br/>
                  I'm especially proud of the variety of outerwear that our merchand=
ising team has put together for fall=2E Sometimes guys overlook the importa=
nce of outerwear and stick with their performance fleeces or ski parkas, bu=
t there is always a better option=2E Your coat, jacket, or vest might be th=
e last thing you put on before you leave the house, but it's one of the fir=
st things people notice=2E
                </td>
              </tr>

              <tr>
                <td class=3D=22spacer40=22 height=3D=2240=22 align=3D=22center=22>
                </td>
              </tr>
            =09
            =09
            =09
            =09
            =09
              <tr>
                <td class=3D=22force-col=22 valign=3D=22top=22>
                  <img class=3D=22fluidimage=22 width=3D=22520=22 src=3D=22https://s=
tatic=2Ecdn=2Eresponsys=2Enet/i5/responsysimages/trnkclb/contentlibrary/adh=
oc2014/2014-09/20140919_Fall/images/DOJS_Blazers_email=2Ejpg=22 style=3D=22=
display:block; border:0;=22 border=3D=220=22 />    =09
                </td>
              </tr>
            =09
              <tr>
                <td class=3D=22spacer10=22 height=3D=2210=22 align=3D=22center=22>
                </td>
              </tr>
            =09

=09
              <tr>
                <td class=3D=22imgcaption=22 align=3D=22left=22 style=3D=22font-siz=
e: 14px;font-family: Georgia, 'Times New Roman', serif; line-height: 24px;=
=22><span style=3D=22font-size: 13px; font-family: Verdana, Helvetica, Aria=
l, san-serif; line-height: 24px; text-transform:uppercase;font-weight:bold=
=22>great britain, great fabrics</span><br/>
                  I have never been to Ireland or the Scottish Highlands, but that d=
oesn't stop me from dressing like I own country estates in both locations=
=2E The Brits discovered that tweed and other sturdy fabrics stood up again=
st cold winds coming off the moors=2E Lucky for us, those same fabrics keep=
 Americans equally warm when temperatures drop on our side of the Atlantic=
=2E
                </td>
              </tr>
              <tr>
                <td class=3D=22spacer40=22 height=3D=2240=22 align=3D=22center=22>
                </td>
              </tr>

<tr>
                <td class=3D=22force-col=22 valign=3D=22top=22>
                  <img class=3D=22fluidimage=22 width=3D=22520=22 src=3D=22https://s=
tatic=2Ecdn=2Eresponsys=2Enet/i5/responsysimages/trnkclb/contentlibrary/adh=
oc2014/2014-09/20140919_Fall/images/DOJS_Howto_Scarf_Email=2Ejpg=22 style=
=3D=22display:block; border:0;=22 border=3D=220=22 />    =09
                </td>
              </tr>
            =09
              <tr>
                <td class=3D=22spacer10=22 height=3D=2210=22 align=3D=22center=22>
                </td>
              </tr>
            =09

=09
              <tr>
                <td class=3D=22imgcaption=22 align=3D=22left=22 style=3D=22font-siz=
e: 14px;font-family: Georgia, 'Times New Roman', serif; line-height: 24px;=
=22><span style=3D=22font-size: 13px; font-family: Verdana, Helvetica, Aria=
l, san-serif; line-height: 24px; text-transform:uppercase;font-weight:bold=
=22>=22Football=22 and Neck Scarves</span><br/>
                  Scarves do a great job of balancing style and function=2E In addit=
ion to keeping the chill off your neck, they add a sophisticated dimension =
to your outfit=2E I prefer the slip knot because it's simple and practical=
=2E It's also the preferred knot of Europe's best-dressed soccer coaches, a=
nd it works just as well for me while I watch Griffin, my two-year-old son,=
 play in his Lil' Kickers soccer league=2E
                </td>
              </tr>
              <tr>
                <td class=3D=22spacer40=22 height=3D=2240=22 align=3D=22center=22>
                </td>
              </tr>
<tr>
                <td class=3D=22force-col=22 valign=3D=22top=22>
                  <img class=3D=22fluidimage=22 width=3D=22520=22 src=3D=22https://s=
tatic=2Ecdn=2Eresponsys=2Enet/i5/responsysimages/trnkclb/contentlibrary/adh=
oc2014/2014-09/20140919_Fall/images/DOJS_Records_Email=2Ejpg=22 style=3D=22=
display:block; border:0;=22 border=3D=220=22 />    =09
                </td>
              </tr>
            =09
              <tr>
                <td class=3D=22spacer10=22 height=3D=2210=22 align=3D=22center=22>
                </td>
              </tr>
            =09

=09
              <tr>
                <td class=3D=22imgcaption=22 align=3D=22left=22 style=3D=22font-siz=
e: 14px;font-family: Georgia, 'Times New Roman', serif; line-height: 24px;=
=22><span style=3D=22font-size: 13px; font-family: Verdana, Helvetica, Aria=
l, san-serif; line-height: 24px; text-transform:uppercase;font-weight:bold=
=22>Everything Old Is New Again</span><br/>
                  For me, fall means nesting time=2E My family, the fireplace, and P=
inot Noir all factor into that=2E I also recently inherited my father's old=
 vinyl collection=2E Beyond listening to the same records that my father us=
ed to blast on weekend mornings (the man refused to let me sleep in), I've =
started to build my own collection=2E =22Paul's Boutique=22 by the Beastie =
Boys and =22Purple Rain=22 by Prince are my two favorite acquisitions so fa=
r=2E
                </td>
              </tr>
            =09


            =09
              <tr>
                <td class=3D=22spacer20=22 height=3D=2220=22 align=3D=22center=22>
                </td>
              </tr>
            =09
              <tr>
                <td align=3D=22center=22 class=3D=22trunkbutton=22 >
                  <table border=3D=220=22 cellpadding=3D=220=22 cellspacing=3D=220=
=22 height=3D=2231=22 style=3D=22height: 31px;margin: 0;padding: 0;=22>
                    <tr>
                      <td align=3D=22center=22 valign=3D=22middle=22 style=3D=22border=
: 2px solid =23000000; font-family: Verdana, Helvetica, Arial, sans-serif;f=
ont-weight: bold;font-size: 9px;text-transform: uppercase;padding: 10px 12p=
x;letter-spacing: 1px;text-align: center;=22>
                        <a href=3D=22https://theclub=2Etrunkclub=2Ecom/pub/cc?_ri_=3DX0=
Gzc2X%3DWQpglLjHJlYQGu7vWlUueJ8ustHD064D0B2pva9AzdairedbwVXtpKX%3DTSTAY&_ei=
_=3DEv_YTMfnCoE7yY4W7cyz-g8PixxlDb9lOyeR0fKf7VWfUYcoICJhe9NaqQ362_KQhy0QtRm=
lkXiJm9OcRg=2E=22 style=3D=22color: =23000000 =21important; text-decoration=
: none;=22>
                          I want fall clothing
                        </a>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            =09
              <tr>
                <td class=3D=22spacer5=22 height=3D=225=22 align=3D=22center=22>
                </td>
              </tr>
          =09
            </table>
          =09
          </td>
        </tr>

      </table>
      <=21-- End White background Container-->
    =09
      <table>=20
        <tr>
          <td height=3D=2220=22 align=3D=22center=22>
          </td>
        </tr>
      </table>
    =09
      <=21-- White background container -->
      <table width=3D=22600=22 class=3D=22container=22 style=3D=22background-c=
olor: =23ffffff; font-family: Georgia, 'Times New Roman', serif; color: =23=
000000;border: 1px solid =23dddddd;=22 border=3D=220=22 bgcolor=3D=22=23fff=
fff=22 cellpadding=3D=220=22 cellspacing=3D=220=22 border=3D=220=22>
        <tr>
        =09
          <td class=3D=22container-padding=22 bgcolor=3D=22=23ffffff=22 align=3D=
=22left=22 valign=3D=22top=22 style=3D=22padding: 20px;=22>
          =09
            <=21-- Stylist Block -->
            <table border=3D=220=22 class=3D=22columns-container=22 style=3D=22ba=
ckground-color: =23ffffff; width:100%;=22 bgcolor=3D=22=23ffffff=22 border=
=3D=220=22 cellpadding=3D=220=22 cellspacing=3D=220=22>
            =09
              <tr>
                <td align=3D=22center=22 class=3D=22sanscaps=22 style=3D=22text-ali=
gn:center; font-size: 11px;font-family: Verdana, Helvetica, Arial, sans-ser=
if; text-transform: uppercase; font-weight: bold; color: =23000000; letter-=
spacing: 1px; line-height: 18px;=22>
                  Reach Me Anytime
                </td>
              </tr>
            =09
              <tr>
                <td align=3D=22center=22 class=3D=22contactinfo=22 style=3D=22text-=
align:center; font-size: 11px;font-family: Verdana, Helvetica, Arial, sans-=
serif; color: =23000000; line-height: 18px;=22>
                  Mary Houlihan<br/>
                  <a href=3D=22mailto:mary=40trunkclub=2Ecom=22 style=3D=22color: =
=23000000 =21important; text-decoration: none =21important;=22>mary=40trunk=
club=2Ecom</a><br/>214=2E306=2E4899<br/>3010 N Henderson Ave=2E Dallas, TX
                </td>
              </tr>
            =09
            </table>
          =09
          </td>
        </tr>
      =09
      </table>
    =09
    </td>
  </tr>

  <tr>
    <td height=3D=2260=22 align=3D=22center=22>
    </td>
  </tr>
=09
  <tr>
    <td class=3D=22footertext=22 align=3D=22center=22 style=3D=22color:=23bbb=
bbb; font-size: 11px; line-height: 14px; font-family: Verdana, Helvetica, A=
rial, sans-serif;=22>
      <a href=3D=22https://theclub=2Etrunkclub=2Ecom/pub/sf/ResponseForm?_ri_=
=3DX0Gzc2X%3DWQpglLjHJlYQGu7vWlUueJ8ustHD064D0B2pva9AzdairedbwVXMtX%3DWQpgl=
LjHJlYQGoglRzbLSq5JlYzfzaormzgRyK8Je71vt63uR284&_ei_=3DEv_YTMfnCoE7yY4W7cyz=
-g8PixxlDb9lOyeR0fKf7VWfUYcoICJhe9NaqQ362_KQhy0QtRmlkXiJm9OcRg=22 style=3D=
=22color:=23bbbbbb;=22>View in your web browser</a>=2E<br/>
      <Br/>
      <a href=3D=22https://theclub=2Etrunkclub=2Ecom/pub/optout?_ri_=3DX0Gzc2X=
%3DWQpglLjHJlYQGu7vWlUueJ8ustHD064D0B2pva9Azdairedbw&_ei_=3DEolaGGF4SNMvxFF=
7KucKuWO1AprnsXfb8XO866Tv3U1ntIHCsC7xkr-TtqJeZS2FtK5pJlbB8_gGxBct6M=22 styl=
e=3D=22color:=23bbbbbb;=22>Unsubscribe</a> from our newsletters=2E<br/>
      <br/>
      Trunk Club<br/>
      325 West Ohio Street<br/>
      Chicago, IL 60654<br/>
      <br/>
  =09
    </td>
  </tr>
=09
=09
</table><br>
<br><img border=3D=220=22 width=3D=223=22 height=3D=223=22 src=3D=22https:/=
/theclub=2Etrunkclub=2Ecom/pub/as?_ri_=3DX0Gzc2X%3DWQpglLjHJlYQGu7vWlUueJ8u=
stHD064D0B2pva9AzdairedbwVXHkMX%3Dw&_ei_=3DEv_YTMfnCoE7yY4W7cyz-g8PixxlDb9l=
OyeR0fKf7VWfUYcoICJhe9NaqQ362_KQhy0QtRmlkXiJm9OcRg=2E=22>




</body>
</html>

------alt_border_GdKj5BwvV4_1--

------msg_border_vJIfNhkUj6--
