Delivered-To: nick@mediauniversal.com
Received: by 10.25.146.21 with SMTP id u21csp248217lfd;
        Mon, 22 Sep 2014 07:02:22 -0700 (PDT)
X-Received: by 10.66.66.163 with SMTP id g3mr3989496pat.150.1411394541482;
        Mon, 22 Sep 2014 07:02:21 -0700 (PDT)
Return-Path: <service@theclub.trunkclub.com>
Received: from omp.theclub.trunkclub.com (omp.theclub.trunkclub.com. [199.7.206.167])
        by mx.google.com with ESMTP id xm6si15874420pab.111.2014.09.22.07.02.20
        for <nick@mediauniversal.com>;
        Mon, 22 Sep 2014 07:02:21 -0700 (PDT)
Received-SPF: pass (google.com: domain of service@theclub.trunkclub.com designates 199.7.206.167 as permitted sender) client-ip=199.7.206.167;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of service@theclub.trunkclub.com designates 199.7.206.167 as permitted sender) smtp.mail=service@theclub.trunkclub.com;
       dkim=pass header.i=@theclub.trunkclub.com;
       dmarc=pass (p=NONE dis=NONE) header.from=theclub.trunkclub.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=trunkclub; d=theclub.trunkclub.com;
 h=MIME-Version:Content-Type:Date:To:From:Reply-To:Subject:Message-ID; i=service@theclub.trunkclub.com;
 bh=1Ga6jpP5N+AOnh2yYrX8coOcZqY=;
 b=CU/SuZa7cNaUd6N+b3VziXkZeq0eRvUH6enU0ZhCn5NgWp3cvQ1lWa0FBH3Bco0SlHWWwnN+jjMy
   oFfSr84zg1hyKUiNdcHcqv2rDAs4o5C1mQH8CQCHsPd/Bde3dNDIt990spVINFG5w3rrDTDvAELR
   22aBRH2s4ZTDMCtEcmc=
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=trunkclub; d=theclub.trunkclub.com;
 b=V78NPNPSyS6z4ELryfCto67jbaFMH6wnlFm1MKe9Pdty9lDeT4m37XUz9avFLqu5IakKaNFM57rF
   mmXeyXAeyYPKFFo1YP0zioNnomMQYcaV/6z8J6X9Qq4MoTgjR6pzm5LU+vLqB3zJrN+c6JYktOCf
   bJO/bSQ0H2vzEsQ0cug=;
Received: by omp.theclub.trunkclub.com id h40luq1607gk for <nick@mediauniversal.com>; Mon, 22 Sep 2014 07:02:20 -0700 (envelope-from <service@theclub.trunkclub.com>)
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----msg_border_1rXmagK5Cz"
Date: Mon, 22 Sep 2014 07:02:20 -0700
To: nick@mediauniversal.com
From: "Mary Houlihan" <service@theclub.trunkclub.com>
Reply-To: "Mary Houlihan" <mary@trunkclub.com>
Subject: Your first trunk
X-sgxh1: gpJsxuLKpHmgpNLjkHtQJhu
X-rext: 4.interact5.EpNbxO-NqJvKf83UAByD0WcCop5Ag2145FpT
X-cid: trnkclb.8165
Message-ID: <0.0.3F.62C.1CFD66DD388F52A.0@omp.theclub.trunkclub.com>

This is a multi-part message in MIME format.

------msg_border_1rXmagK5Cz
Date: Mon, 22 Sep 2014 07:02:20 -0700
Content-Type: multipart/alternative; boundary="----alt_border_kPOy9mV8VH_1"



------alt_border_kPOy9mV8VH_1
Content-Type: text/plain;
  charset="ISO-8859-1"
Content-Transfer-Encoding: quoted-printable

Hi Nick,=20

I'm Mary Houlihan, your=20
Trunk Club stylist=2E  I can't wait to put=20
together your first trunk of great clothes=2E=20

Before I do that, it=92s important that we=20
have a quick phone call, so that I can=20
get an idea of your fit and style=20
preferences=2E=20

Please reply to this email and let me=20
know a good day and time to chat=2E

You can also feel free to call me any=20
time at the number below=2E

Hope to hear from you soon=21

Mary Houlihan
214=2E306=2E4899















Unsubscribe from our newsletters:
https://theclub=2Etrunkclub=2Ecom/pub/optout?_ri_=3DX0Gzc2X%3DWQpglLjHJlYQG=
ivIzfwqvzbcNdMCU367P9R4J8hiY6nTSWYzgi2&_ei_=3DEolaGGF4SNMvxFF7KucKuWO1Aprns=
Xfb8XO866Tv3U1ntIHCsC7xkr-TtqJeZS2FtK5pJlbB8_gGxBct6M=20


Trunk Club=20
325 West Ohio Street=20
Chicago, IL 60654

------alt_border_kPOy9mV8VH_1
Content-Type: text/html;
  charset="ISO-8859-1"
Content-Transfer-Encoding: quoted-printable

<=21DOCTYPE html PUBLIC =22-//W3C//DTD HTML 4=2E01 Transitional//EN=22 =22h=
ttp://www=2Ew3=2Eorg/TR/html4/loose=2Edtd=22>
<html lang=3D=22en=22>
<head><META NAME=3D=22ROBOTS=22 CONTENT=3D=22NOINDEX, NOFOLLOW=22>
    <meta http-equiv=3D=22Content-Type=22 content=3D=22text/html; charset=
=3DUTF-8=22>
    <meta http-equiv=3D=22Cache-Control=22 content=3D=22no-cache; max-age=
=3D0=22>
    <meta name=3D=22viewport=22 content=3D=22initial-scale=3D1=2E0=22/>   <=
=21-- So that mobile webkit will display zoomed in -->
    <meta name=3D=22format-detection=22 content=3D=22telephone=3Dno;address=
=3Dno;email=3Dno=22>
  =09
  =09

      <title>Trunk Club</title>=20
<style type=3D=22text/css=22>
  /* Resets: see reset=2Ecss for details */
  =2EReadMsgBody =7B width: 100%; background-color: =23e6e6e6;=7D
  =2EExternalClass =7Bwidth: 100%; background-color: =23e6e6e6;=7D
  =2EExternalClass, =2EExternalClass p, =2EExternalClass span, =2EExternalCl=
ass font, =2EExternalClass td, =2EExternalClass div =7Bline-height:100%;=7D
  body =7B-webkit-text-size-adjust:none; -ms-text-size-adjust:none;=7D
  body =7Bmargin:0; padding:0;=7D
  table =7Bborder-spacing:0;=7D
  table td =7Bborder-collapse:collapse;=7D
  =2Eyshortcuts a =7Bborder-bottom: none =21important;=7D
  =2Epreheader =7B display:none =21important; visibility:hidden; opacity:0; =
color:transparent; height:0; width:0; =7D
  =2Ebodycopy=7Btext-align:center; font-size: 13px;font-family: arial, Helve=
tica, sans-serif; line-height: 24px;=7D

  /* Make sure bg is still visible on mobile */
  =40media screen and (max-width: 600px) =7B
    table=5Bclass=3D=22container=22=5D =7B
      width: 95% =21important;
    =7D
  =7D

  /* Less padding on mobile */
  =40media screen and (max-width: 480px) =7B
    td=5Bclass=3D=22container-padding=22=5D =7B
      padding: 15px =21important;
    =7D
  =09
  =7D
=09
  /* unzoom view on Windows Phones */
  =40media (max-width: 400px) =7B
    =40-ms-viewport =7B
      width: 320px =21important;
    =7D
  =7D

      </style>
</head>

<body style=3D=22font-family: Helvetica, Arial, Sans-Serif; font-size:14px;=
 margin: 0; padding: 0;=22>


<table border=3D=220=22 style=3D=22width: 500px;=22 width=3D=22500=22 borde=
r=3D=220=22 cellpadding=3D=220=22 cellspacing=3D=220=22>
  <tr>
    <td align=3D=22left=22 class=3D=22container-padding=22 style=3D=22padding=
: 20px;=22>
      <span class=3D=22bodycopy=22 style=3D=22text-align:left; font-size: 13px=
;font-family: Helvetica, Arial, Sans-Serif; line-height: 18px;=22>

        Hi Nick,<br/>
        <br/>
        I'm Mary Houlihan, your Trunk Club stylist=2E  I can't wait to put toge=
ther your first trunk of great clothes=2E Before I do that, it=92s importan=
t that we have a quick phone call, so that I can get an idea of your fit an=
d style preferences=2E <br/>
<br/>
Please reply to this email and let me know a good day and time to chat=2E<b=
r/>
<br/>
You can also feel free to call me any time at the number below=2E<br/>
<br/>
Hope to hear from you soon=21<Br/>
        <br/>
        Mary Houlihan<br/>214=2E306=2E4899<br/>
      </span>
      <br/>
      <br/>
      <br/>
      <br/>=09
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>=09
      <br/>
    </span>
    <span style=3D=22text-align:left; font-size: 12px;font-family: Helvetica,=
 Arial, Sans-Serif; line-height: 16px; color: =23bbbbbb;=22>
      <a href=3D=22https://theclub=2Etrunkclub=2Ecom/pub/optout?_ri_=3DX0Gzc2X=
%3DWQpglLjHJlYQGivIzfwqvzbcNdMCU367P9R4J8hiY6nTSWYzgi2&_ei_=3DEolaGGF4SNMvx=
FF7KucKuWO1AprnsXfb8XO866Tv3U1ntIHCsC7xkr-TtqJeZS2FtK5pJlbB8_gGxBct6M=22 st=
yle=3D=22color:=23bbbbbb;=22>Click here</a> if you wish not to be contacted=
 anymore=2E<br/>
      Trunk Club<br/>
      325 West Ohio Street<br/>
      Chicago, IL 60654<br/>
      <br/>
  =09
    </span></td>
  </tr>
=09
=09
</table><br>
<br><img border=3D=220=22 width=3D=223=22 height=3D=223=22 src=3D=22https:/=
/theclub=2Etrunkclub=2Ecom/pub/as?_ri_=3DX0Gzc2X%3DWQpglLjHJlYQGivIzfwqvzbc=
NdMCU367P9R4J8hiY6nTSWYzgi2VXHkMX%3Dw&_ei_=3DEv_YTMfnCoE7yY4W7cyz-g8PixxlDb=
9lOyeR0fKf7VWfUYcoICJhe9NaqQ362_KQhy0QtRmlkXiJm9OcRg=2E=22>




</body>
</html>

------alt_border_kPOy9mV8VH_1--

------msg_border_1rXmagK5Cz--
